title: Beproefd!!
author: Esther
description: Een verzameling van favoriete recepten
url: ""
baseurl: "/recepten"  # Lokaal testen: "" / GitHub Pages: "/recepten"

# Jekyll instellingen
theme: null
plugins: []

# Collecties
collections:
  recepten:
    output: true
    permalink: /recepten/:slug/
  categorie:
    output: true
    permalink: /categorie/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "recepten"
    values:
      layout: "recept"
  - scope:
      path: ""
      type: "categorie"
    values:
      layout: "categorie"

# Uitsluiting bestanden
exclude:
  - Gemfile
  - Gemfile.lock
  - README.adoc
  - .vscode/

# Build instellingen
markdown: kramdown
highlighter: rouge
lsi: false
safe: true
incremental: false
